/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-09-16 13:09:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.util.*;
import java.sql.*;
import javax.servlet.http.*;
import javax.servlet.*;

public final class TotalHome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1631523649657L));
    _jspx_dependants.put("jar:file:/D:/PRO2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Hw2Test/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/sql.tld", Long.valueOf(1425949870000L));
    _jspx_dependants.put("jar:file:/D:/PRO2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Hw2Test/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425949870000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsql_005fsetDataSource_0026_005fvar_005fuser_005furl_005fpassword_005fdriver_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsql_005fquery_0026_005fvar_005fdataSource;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsql_005fsetDataSource_0026_005fvar_005fuser_005furl_005fpassword_005fdriver_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsql_005fquery_0026_005fvar_005fdataSource = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsql_005fsetDataSource_0026_005fvar_005fuser_005furl_005fpassword_005fdriver_005fnobody.release();
    _005fjspx_005ftagPool_005fsql_005fquery_0026_005fvar_005fdataSource.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("		<meta charset=\"utf-8\" />\r\n");
      out.write("		<title>BuyBuyLa購物商城</title>\r\n");
      out.write("		<!--商品列表样式表-->\r\n");
      out.write("		<link rel=\"stylesheet\" type=\"text/css\" href=\"TotalHome.css\" />\r\n");
      out.write("		<!--cookie操作的js库-->\r\n");
      out.write("\r\n");
      out.write("		<script src=\"cookie.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("		<style>\r\n");
      out.write("\r\n");
      out.write("	@import url('https://fonts.googleapis.com/css2?family=Patrick+Hand&display=swap');\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* HTML5 display-role reset for older browsers */\r\n");
      out.write("\r\n");
      out.write("html, body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p,\r\n");
      out.write("	blockquote, pre, a, abbr, acronym, address, big, cite, code, del, dfn,\r\n");
      out.write("	em, img, ins, kbd, q, s, samp, small, strike, strong, sub, sup, tt, var,\r\n");
      out.write("	b, u, i, center, dd, ol, ul, li, fieldset, form, label, legend,\r\n");
      out.write("	table, caption, tbody, tfoot, thead, tr, th, td, article, aside, canvas,\r\n");
      out.write("	details, embed, figure, figcaption, footer, header, hgroup, menu, nav,\r\n");
      out.write("	output, ruby, section, summary, time, mark, audio, video {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	border: 0;\r\n");
      out.write("	font: inherit;\r\n");
      out.write("	vertical-align: baseline;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("ol, ul {\r\n");
      out.write("	list-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("blockquote, q {\r\n");
      out.write("	quotes: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("blockquote:before, blockquote:after, q:before, q:after {\r\n");
      out.write("	content: '';\r\n");
      out.write("	content: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("	border-collapse: collapse;\r\n");
      out.write("	border-spacing: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ---CSS reset is above--- */\r\n");
      out.write("* {\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 80px;\r\n");
      out.write("	background: rgb(203, 218, 218);\r\n");
      out.write("	color: white;\r\n");
      out.write("	font-size: 50px;\r\n");
      out.write("	padding-left: 30px;\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	z-index: 5000;\r\n");
      out.write("	font-family: 'Patrick Hand', cursive;\r\n");
      out.write("	font-weight:600;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box {\r\n");
      out.write("	border-radius: 10%;\r\n");
      out.write("	background: rgb(203, 218, 218);\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	right: 50px;\r\n");
      out.write("	bottom: 30px;\r\n");
      out.write("	z-index: 2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box a {\r\n");
      out.write("	display: block;\r\n");
      out.write("	width: 70px;\r\n");
      out.write("	height: 70px;\r\n");
      out.write("	padding: 25px 15px;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".productList {\r\n");
      out.write("	width: 960px;\r\n");
      out.write("	margin: 120px auto;\r\n");
      out.write("	z-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".productList img {\r\n");
      out.write("	width: 60%;\r\n");
      out.write("	margin-top: 30px;\r\n");
      out.write("	margin-left: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".productList li {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	float: left;\r\n");
      out.write("	width: 220px;\r\n");
      out.write("	height: 310px;\r\n");
      out.write("	border: 1px dotted rgb(203, 218, 218);\r\n");
      out.write("	margin-left: 10px;\r\n");
      out.write("	margin-right: 10px;\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("	padding-right: 5px;\r\n");
      out.write("	padding-left: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".productList .sale {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	background: rgb(203, 218, 218);\r\n");
      out.write("	color: rgb(203, 218, 218);\r\n");
      out.write("	padding: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".productList li h2 {\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	color: #000000;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("	margin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".productList li span {\r\n");
      out.write("	color: rgb(138, 221, 221);\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button {\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	display: block;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	max-width: 130px;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	border-radius: 4px;\r\n");
      out.write("	padding: 10px 30px;\r\n");
      out.write("	font-size: small;\r\n");
      out.write("	border: 1px solid gainsboro;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("button:hover {\r\n");
      out.write("	color: rgba(255, 255, 255, 0.85);\r\n");
      out.write("	border: none;\r\n");
      out.write("	background-color: #3498db;\r\n");
      out.write("	opacity:0.5;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write(".demo-footer {\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	bottom: 0;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	padding: 15px;\r\n");
      out.write("	background-color: #212121;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	\r\n");
      out.write("	opacity:0.1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".demo-footer > a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("}\r\n");
      out.write(".modal-content {\r\n");
      out.write("		border-radius: 0;\r\n");
      out.write("		border: none;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.modal-header {\r\n");
      out.write("		border-bottom-color: #EEEEEE;\r\n");
      out.write("		background-color: #FAFAFA;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("nav{\r\n");
      out.write(" 	float:right;\r\n");
      out.write(" 	position: fixed;\r\n");
      out.write(" 	 top:0;\r\n");
      out.write(" 	 right:0;\r\n");
      out.write(" 	 z-index: 6000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul{\r\n");
      out.write("  margin: 10px 0;\r\n");
      out.write("  padding: 0px;\r\n");
      out.write("  list-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.dropdown{ \r\n");
      out.write("  position: relative; \r\n");
      out.write("  width: 100%; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.dropdown li{ \r\n");
      out.write("  font-weight: bold; \r\n");
      out.write("  float: left; \r\n");
      out.write("  width: 110px; \r\n");
      out.write("  position: relative;\r\n");
      out.write("  background: #ecf0f1;\r\n");
      out.write("  opacity:0.6;\r\n");
      out.write("  margin-right:5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("ul.dropdown a:hover{ \r\n");
      out.write("  color: #000; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("ul.dropdown li a { \r\n");
      out.write("  display: block; \r\n");
      out.write("  padding: 20px 8px;\r\n");
      out.write("  color: rgb(3, 0, 0); \r\n");
      out.write("  position: relative; \r\n");
      out.write("  z-index: 2000; \r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  font-weight: 350;\r\n");
      out.write("  font-size:small;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.dropdown li a:hover,\r\n");
      out.write("ul.dropdown li a.hover{ \r\n");
      out.write("  background: #3498db;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("ul.dropdown ul{ \r\n");
      out.write(" display: none;\r\n");
      out.write(" position: absolute; \r\n");
      out.write("  width: 180px; \r\n");
      out.write("  z-index: 1000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.dropdown ul li { \r\n");
      out.write("  font-weight: normal; \r\n");
      out.write("  background: #f6f6f6; \r\n");
      out.write("  color: #000; \r\n");
      out.write("  border-bottom: 1px solid #ccc; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.dropdown ul li a{ \r\n");
      out.write("  display: block; \r\n");
      out.write("  color: #34495e !important;\r\n");
      out.write("  background: #eee !important;\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("ul.dropdown ul li a:hover{\r\n");
      out.write("  display: block; \r\n");
      out.write("  background: #3498db !important;\r\n");
      out.write("  color: #fff !important;\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("ul.dropdown ul li a i{\r\n");
      out.write("		color:red;\r\n");
      out.write("}\r\n");
      out.write(".drop > a{\r\n");
      out.write("  position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".drop > a:after{\r\n");
      out.write("  content:\"\";\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  right: 10px;\r\n");
      out.write("  border-left: 5px solid transparent;\r\n");
      out.write("  border-top: 5px solid #333;\r\n");
      out.write("  border-right: 5px solid transparent;\r\n");
      out.write("  z-index: 999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".drop > a:hover:after{\r\n");
      out.write(" 	 content:\"\";\r\n");
      out.write("   border-left: 5px solid transparent;\r\n");
      out.write("  border-top: 5px solid #fff;\r\n");
      out.write("  border-right: 5px solid transparent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</style>\r\n");
      out.write("	\r\n");
      out.write("	</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <nav>\r\n");
      out.write("<ul class=\"dropdown\">\r\n");
      out.write("        	<li ><a href=\"index.jsp\" >我的購物車(<i id=\"ccount\">0</i>)</a>\r\n");
      out.write("        	\r\n");
      out.write("        	</li>\r\n");
      out.write("        	<li ><a href=\"main.html\">活動專區</a>\r\n");
      out.write("        		\r\n");
      out.write("        	</li>\r\n");
      out.write("        	<li ><a href=\"Intelligence32.jsp\">團購專區</a>\r\n");
      out.write("        		\r\n");
      out.write("        	</li>\r\n");
      out.write("        	<li><a href=\"UserLogin.jsp\">會員登入</a>\r\n");
      out.write("        	</li>\r\n");
      out.write(" 			<li><a href=\"Form.jsp\">會員註冊</a>\r\n");
      out.write("        	</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("</nav> \r\n");
      if (_jspx_meth_sql_005fsetDataSource_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_sql_005fquery_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"header\" >\r\n");
      out.write("			BuyBuyLa <span style=\"font-size:30 ;color:#fff ; font-weight:200;\">× Make money what you like</span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"box\">\r\n");
      out.write("			<a href=\"#\">TOP</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"mycar\">\r\n");
      out.write("			\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"List\">\r\n");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<footer class=\"demo-footer\">\r\n");
      out.write("	<a href=\"./AllProduct.jsp\" target=\"_blank\">商品管理</a>\r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\" src=\"server.js\"></script>\r\n");
      out.write("		<!--\r\n");
      out.write("        	描述：本页面的js操作\r\n");
      out.write("        -->\r\n");
      out.write("		<script type=\"text/javascript\" src=\"test.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_sql_005fsetDataSource_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sql:setDataSource
    org.apache.taglibs.standard.tag.rt.sql.SetDataSourceTag _jspx_th_sql_005fsetDataSource_005f0 = (org.apache.taglibs.standard.tag.rt.sql.SetDataSourceTag) _005fjspx_005ftagPool_005fsql_005fsetDataSource_0026_005fvar_005fuser_005furl_005fpassword_005fdriver_005fnobody.get(org.apache.taglibs.standard.tag.rt.sql.SetDataSourceTag.class);
    boolean _jspx_th_sql_005fsetDataSource_005f0_reused = false;
    try {
      _jspx_th_sql_005fsetDataSource_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sql_005fsetDataSource_005f0.setParent(null);
      // /TotalHome.jsp(319,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sql_005fsetDataSource_005f0.setVar("snapshot");
      // /TotalHome.jsp(319,0) name = driver type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sql_005fsetDataSource_005f0.setDriver("com.microsoft.sqlserver.jdbc.SQLServerDriver");
      // /TotalHome.jsp(319,0) name = url type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sql_005fsetDataSource_005f0.setUrl("jdbc:sqlserver://localhost:1433;databaseName=BuyBuy");
      // /TotalHome.jsp(319,0) name = user type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sql_005fsetDataSource_005f0.setUser("sa");
      // /TotalHome.jsp(319,0) name = password type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sql_005fsetDataSource_005f0.setPassword("123123123");
      int _jspx_eval_sql_005fsetDataSource_005f0 = _jspx_th_sql_005fsetDataSource_005f0.doStartTag();
      if (_jspx_th_sql_005fsetDataSource_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsql_005fsetDataSource_0026_005fvar_005fuser_005furl_005fpassword_005fdriver_005fnobody.reuse(_jspx_th_sql_005fsetDataSource_005f0);
      _jspx_th_sql_005fsetDataSource_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sql_005fsetDataSource_005f0, _jsp_getInstanceManager(), _jspx_th_sql_005fsetDataSource_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sql_005fquery_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sql:query
    org.apache.taglibs.standard.tag.rt.sql.QueryTag _jspx_th_sql_005fquery_005f0 = (org.apache.taglibs.standard.tag.rt.sql.QueryTag) _005fjspx_005ftagPool_005fsql_005fquery_0026_005fvar_005fdataSource.get(org.apache.taglibs.standard.tag.rt.sql.QueryTag.class);
    boolean _jspx_th_sql_005fquery_005f0_reused = false;
    try {
      _jspx_th_sql_005fquery_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sql_005fquery_005f0.setParent(null);
      // /TotalHome.jsp(323,0) name = dataSource type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sql_005fquery_005f0.setDataSource((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${snapshot}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /TotalHome.jsp(323,0) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sql_005fquery_005f0.setVar("result");
      int[] _jspx_push_body_count_sql_005fquery_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_sql_005fquery_005f0 = _jspx_th_sql_005fquery_005f0.doStartTag();
        if (_jspx_eval_sql_005fquery_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspx_eval_sql_005fquery_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            _jspx_push_body_count_sql_005fquery_005f0[0]++;
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_sql_005fquery_005f0);
          }
          do {
            out.write("\r\n");
            out.write("SELECT * from PRODUCT;\r\n");
            int evalDoAfterBody = _jspx_th_sql_005fquery_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_sql_005fquery_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
            _jspx_push_body_count_sql_005fquery_005f0[0]--;
          }
        }
        if (_jspx_th_sql_005fquery_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sql_005fquery_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sql_005fquery_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sql_005fquery_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fsql_005fquery_0026_005fvar_005fdataSource.reuse(_jspx_th_sql_005fquery_005f0);
      _jspx_th_sql_005fquery_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sql_005fquery_005f0, _jsp_getInstanceManager(), _jspx_th_sql_005fquery_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /TotalHome.jsp(338,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("row");
      // /TotalHome.jsp(338,0) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/TotalHome.jsp(338,0) '${result.rows}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${result.rows}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\r\n");
            out.write("				<dl pid=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.PID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("					<dt>\r\n");
            out.write("						<img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.P_img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" />\r\n");
            out.write("					</dt>\r\n");
            out.write("					<dd><span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.P_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span></dd>\r\n");
            out.write("					\r\n");
            out.write("					<dd><span style=\"color:red\">$");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.P_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span></dd>\r\n");
            out.write("					<dd>\r\n");
            out.write("						<button>加入購物車</button>\r\n");
            out.write("						\r\n");
            out.write("					</dd>\r\n");
            out.write("				</dl> \r\n");
            out.write("			\r\n");
            out.write("			\r\n");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
